export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DiscoverLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>{children}</>
  )
}
