[build]
  command = "cd malk-nextjs && npm run build"
  publish = "malk-nextjs/.next"
  functions = "netlify/functions"

[dev]
  command = "cd malk-nextjs && npm run dev"
  port = 3000
  targetPort = 3000
  publish = "malk-nextjs/.next"
  functions = "netlify/functions"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["firebase-admin"]

[build.environment]
  NODE_VERSION = "18" 